export enum ACTIONS_TYPE {
    SET_USER_DATA = 'SET_USER_DATA',
    INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS',

    SET_APP_STATUS = 'SET_APP_STATUS',

    REMOVE_TASK = 'REMOVE_TASK',
    ADD_TASK = 'ADD_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    SET_TASKS = "SET_TASKS",

    REMOVE_TODOLIST = 'REMOVE_TODOLIST',
    ADD_TODOLIST = 'ADD_TODOLIST',
    CHANGE_TODOLIST_TITLE = 'CHANGE_TODOLIST_TITLE',
    CHANGE_TODOLIST_FILTER = 'CHANGE_TODOLIST_FILTER',
    SET_TODOLISTS = 'SET_TODOLISTS',
}
